### ISSUE TITLE
badly formatted make file????

### ISSUE THREAD

**Issue by hmaarrfk** [Archiconda/m4-feedstock#1]
Bad formatting of the resulting makefile
@jjhelmus any idea why the makefile is badly formatted:

https://app.shippable.com/github/Archiconda/m4-feedstock/runs/4/1/console

```
+ make -j96
GNUmakefile:34: *** missing separator.  Stop.
source tree in: /root/archiconda3/conda-bld/m4_1546657925394/work
```

Anyway, I tried to pin to an older version of make (that I have on ubuntu 18.04) https://app.shippable.com/github/Archiconda/m4-feedstock/runs/6/1/console

**Comment by jjhelmus** [comment]
See Archiconda/make-make-feedstock#2

**Comment by hmaarrfk** [comment]
Thanks!
